//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _23dh114467_NamStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        public int ProDeID { get; set; }
        public int ProductID { get; set; }
        public decimal Price { get; set; }
        public int RemainQuantity { get; set; }
        public int SoldQuantity { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
